default:
	avr-gcc -Os -DF_CPU=16000000UL -mmcu=atmega328p led.c -o led.elf -I /usr/avr/include
	avr-objcopy -O ihex -j .text -j .data led.elf led.hex
	sudo avrdude -c arduino -p ATMEGA328P -P /dev/ttyACM0 -b 115200 -u flash:w:led.hex
